<?php

namespace Tests\Unit;

use App\Exceptions\ValidationFaildException;
use App\Services\UserValidationService;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserValidationTest extends TestCase
{
    private $userValidationService;

    private const CREDENTIALS = [
        'email' => 'test@gmal.com',
        'password' => 'secret',
        'name' => 'UserTestName'
    ];
    private const WRONG_CREDENTIALS = [
        'email' => 'testgmalcom',
        'password' => 'sec',
        'name' => 'UserTestName'
    ];
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->userValidationService = new UserValidationService();
    }

    /**
     * @return void
     * @throws ValidationFaildException
     */
    public function testWrongCredentials()
    {
        $credentials = self::WRONG_CREDENTIALS;
        $this->expectException(ValidationFaildException::class);

        $this->userValidationService->validateUser($credentials);
    }

    /**
     * @throws ValidationFaildException
     */
    public function testSuccessCredentials()
    {
        $credentials = self::CREDENTIALS;
        $this->userValidationService->validateUser($credentials);

        $this->assertEmpty($this->userValidationService->errors());
    }
}
